
services:
  postgres_db:
    image: postgres:latest
    container_name: todo_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"  # Map local port 5432 to the container's port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data even if the container is removed
    restart: unless-stopped

volumes:
  postgres_data:
  